// File generated by FlutterFire CLI.
// This file is safe to check into version control.
// 
// You MUST replace the placeholder values below with your actual Firebase project settings.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for different platforms.
///
/// NOTE: You MUST replace the placeholder values in this file with your
/// project-specific settings. Consult the official FlutterFire documentation.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return const FirebaseOptions(
        apiKey: 'AIzaSyCahMIf5Q3YBsjfXB30YpAgWfycvT0gCqQ', // <-- REPLACE THIS
        appId: '1:267189664335:web:ad23fb36b6aabfc52e883a', // <-- REPLACE THIS
        messagingSenderId: '267189664335', // <-- REPLACE THIS
        projectId: 'grandslogistics-8af41', // <-- REPLACE THIS
        authDomain: 'grandslogistics-8af41.firebaseapp.com', // <-- REPLACE THIS
        storageBucket: 'grandslogistics-8af41.firebasestorage.app', // <-- REPLACE THIS
        // Optional:
        // measurementId: 'G-XXXXXXXXXX',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return const FirebaseOptions(
          apiKey: 'YOUR_ANDROID_API_KEY_HERE',
          appId: 'YOUR_ANDROID_APP_ID_HERE',
          messagingSenderId: 'YOUR_MESSAGING_SENDER_ID_HERE',
          projectId: 'YOUR_PROJECT_ID_HERE',
          storageBucket: 'YOUR_PROJECT_ID.appspot.com',
        );
      case TargetPlatform.iOS:
        return const FirebaseOptions(
          apiKey: 'YOUR_IOS_API_KEY_HERE',
          appId: 'YOUR_IOS_APP_ID_HERE',
          messagingSenderId: 'YOUR_MESSAGING_SENDER_ID_HERE',
          projectId: 'YOUR_PROJECT_ID_HERE',
          storageBucket: 'YOUR_PROJECT_ID.appspot.com',
          // Optional:
          // iosBundleId: 'com.example.yourAppName',
        );
      case TargetPlatform.macOS:
        return const FirebaseOptions(
          apiKey: 'YOUR_MACOS_API_KEY_HERE',
          appId: 'YOUR_MACOS_APP_ID_HERE',
          messagingSenderId: 'YOUR_MESSAGING_SENDER_ID_HERE',
          projectId: 'YOUR_PROJECT_ID_HERE',
          storageBucket: 'YOUR_PROJECT_ID.appspot.com',
          // Optional:
          // macosBundleId: 'com.example.yourAppName',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }
}